export {default as Allergies} from './Allergies'
export {default as Cuisines} from './Cuisines'
export {default as Diets} from './Diets'
export {default as Ingredients} from './Ingredients'
export {default as Nutrition} from './Nutrition'
export {default as Tastes} from './Tastes'
export {default as Techniques} from './Techniques'
export {default as Time} from './Time'
